# Generated by Django 4.2.3 on 2023-10-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subj', models.CharField(max_length=20)),
                ('Messa', models.CharField(max_length=20)),
                ('Self_email', models.EmailField(max_length=20)),
                ('Custom_email', models.EmailField(max_length=20)),
            ],
        ),
    ]
