# Generated by Django 4.2.3 on 2023-10-09 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storedata',
            old_name='Custom_email',
            new_name='Customer_email',
        ),
    ]
